blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/orgs/horcrux-framework/discussions/new/choose
    about: Ask questions or request help related to Horcrux
