blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/<your-org-or-username>/<your-repo>/discussions/new
    about: Ask questions or request help related to Horcrux
