name: ❓ Question
description: Ask a question or request clarification
title: '[Question]: '
labels: ['question']
assignees:
  - dgtalbug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out with a question! This form helps us understand and respond more effectively.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we contact you if follow-up is needed?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Ask anything related to Horcrux, its architecture, usage, or roadmap.
      placeholder: ex. How does the plugin system dynamically load modules?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (if applicable)
      description: What are you working on? Why are you asking?
      placeholder: ex. I'm integrating Horcrux with a local Raspberry Pi voice service.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this question, you agree to follow our [Code of Conduct](https://github.com/horcrux-framework/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
